### ISSUE TITLE
OS X dependency path likely broken

### ISSUE THREAD

**Issue by cburgmer** [mclarkson/JSONPath.sh#15]
It seems that the path used in https://github.com/bashtools/JSONPath.sh/blob/ce89800d1f0d4e265fccf69e007ad5ea827edc8a/ensure_deps.sh#L34C22-L34C61 is not valid anymore for the current Homebrew installation. Instead the binaries currently seem to be found under `/opt/homebrew/opt/coreutils/libexec/gnubin`.

Can file a PR when I find more time.

**Comment by lcn2** [comment]
Hello @cburgmer,

Our pull request #16 also addresses your issue, or you may wish to use the [lcn2 JSONPath.sh fork](https://github.com/lcn2/JSONPath.sh).

**Comment by cburgmer** [comment]
Fixed and released under 0.0.19.
