### ISSUE TITLE
 Doesn't work on Mac OS

### ISSUE THREAD

**Issue by ianldgs** [mclarkson/JSONPath.sh#3]
When I try to use JSONPath on Mac OS it outputs the following error:

```
line 250: readarray: command not found
```

**Comment by mclarkson** [comment]
I think `brew install bash` is needed on Mac. Does it work then?

**Comment by ianldgs** [comment]
I already have bash installed:

```bash
~ echo '{"foo": "bar"}' | bash JSONPath.sh '$.foo'                                                                                                                 

JSONPath.sh: line 250: readarray: command not found
```

**Comment by mclarkson** [comment]
The first line needed changing. It was referencing the default system `bash` rather than the `brew install`ed `bash`. Thanks!
